name: Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Chrome
      run: |
        mkdir -p chrome
        cp -R -t chrome *.{js,css,html,json,png}
        rm -f chrome/*-firefox.* chrome/icon.png
        mv chrome/manifest-chrome.json chrome/manifest.json
    - uses: actions/upload-artifact@v2
      with:
        name: chrome
        path: chrome
 
    - name: Firefox
      run: |
        mkdir -p firefox
        cp -R -t firefox *.{js,css,html,json,png}
        rm -f firefox/*-chrome.* firefox/icon.png
        mv chrome/manifest-firefox.json firefox/manifest.json
    - uses: actions/upload-artifact@v2
      with:
        name: firefox
        path: firefox
