name: Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Chrome  
      working-directory: .
      run: mkdir chrome/ && cp -R *.js *.css *.html *.json *.png chrome/ && rm /chrome/firefox-* icon.png && mv /chrome/chrome-manifest.json /chrome/manifest.json
    - uses: actions/upload-artifact@v2
      with:
        name: chrome
        path: chrome
 
    - name: Firefox
      working-directory: .
      run: mkdir firefox/ && cp -R *.js *.css *.html *.json *.png firefox/ && rm /firefox/chrome-* icon.png
    - uses: actions/upload-artifact@v2
      with:
        name: firefox
        path: firefox
