name: Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Chrome
      run: mkdir ./chrome && cp *.js *.css *.html *.png /chrome && rm /chrome/firefox-* icon.png
    - uses: actions/upload-artifact@v2
      with:
        name: chrome
        path: ./chrome
 
    - name: Firefox
      run: mkdir ./firefox && cp *.js *.css *.html *.png ./firefox && rm ./firefox/chrome-* icon.png
    - uses: actions/upload-artifact@v2
      with:
        name: firefox
        path: ./firefox
