name: Builds

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Create artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Chrome
    - uses: actions/upload-artifact@v2
      with:
        name: chrome
        path: chrome
    - run: cp *.js *.css *.html *.png /chrome && rm /chrome/firefox-* icon.png
 
    - name: Firefox
    - uses: actions/upload-artifact@v2
      with:
        name: firefox
        path: firefox
    - run: cp *.js *.css *.html *.png /chrome && rm /firefox/chrome-* icon.png
