name: Codecov

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Codecov
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
